### ISSUE TITLE
Restore Original MailEditor Dialog Layout

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#100]
Please restore the original MailEditor, the new layout is hideous.  Everything that was there was for a reason.

In the future, any changes to the GUI layout must be approved.  Please stick to making the existing layout FUNCTIONAL rather than completely tossing everything I have done.

**Comment by vogel76** [comment]
Formatting toolbar hidden by default (and added back explicit button to show/hide it). This btn was initially removed since the same functionality is available from context menu configured to this window (allows to show/hide any of defined toolbars there).
Implemented at rev:
https://github.com/InvictusInnovations/keyhotee/commit/1485b0c833849e04609187197afeb05856d2dc33
