### ISSUE TITLE
Move Attachment bucket below the FORMAT BAR not beside the TO fields.

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#101]
Adjust its size so that it is no taller than necessary to fit the content.

**Comment by vogel76** [comment]
Already moved to bottom of the email window as it was initially specified in todo.txt (this request has been issued after implemented). Anyway since attachment list is placed on toolbar it can be moved by user below mail fields toolbar.
Done at rev:
https://github.com/InvictusInnovations/keyhotee/commit/1485b0c833849e04609187197afeb05856d2dc33
