### ISSUE TITLE
Lack unique comparison for bts::bitchat::message_header struct

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#107]
It is impossible to uniquely identify these objects what leads to problems in Draft messages overwriting:
- since gui (MailBox view => MailboxModel) is not able to find existing one message in its data structures redundant row is added each time Draft message is saved (even it was just opened for another edit)
- calling message_db::store after adding new saved message removes this new one, not message_header passed for previous version. This leads gui to crash when someone tries to refresh messageview (it refers to nonexisting message_header in storage)
  To reproduce this behaviour one line must be commented out in
  TMailProcessor::Save method:
  msgToOverwrite = nullptr;
  Next open new message, fill it with some contents and save. Next open from Draft folder again, modify and save again. Crash will occur.

**Comment by dnotestein** [comment]
After some analysis, I decided safest thing was to make some minor modifications to backend api to reduce the chance for errors. The key thing with this api is that each message saved into the database needs a unique sig_time. For draft messages, the sig_time should be slightly abused since there is no real signature time. Instead, I just used the time that the draft message is being saved.

I made a minor modification to use optional instead of draft message, boolean pair, since optional more clearly shows the pattern being used I think.

I left some other comments in the code related to how we're storing drafts that may need further discussion. I suspect the code was written the way it is (sign/encrypting/decrypting) in order to make sure the sig_time got set to avoid the consequent problems, but I think it's overkill, only sig_time needs to be set. There was also a misleading comment in message_db api that implied that messages were saved encrypted, which could have also caused some initial confusion.

I am seeing an error in the "to" field of the draft folder, but I don't think it's a backend problem. I can debug it tomorrow, unless someone works it out before then.
