### ISSUE TITLE
At latest Bitshares revision application hangs at startup

### ISSUE THREAD

**Issue by vogel76** [InvictusInnovations/keyhotee#108]
https://github.com/InvictusInnovations/BitShares/commit/f6c14929ea95c80e14779f57dfb397bda088c567
Try to start the application, it hangs. Probably it is caused by connectivity problem to configured external server and it looks bad since nothing is displayed to the user (except internal debug log). I think first main window should be displayed, next network connection established in another thread to display some progress status (at least message "connecting to <ip>... " on status bar.

**Comment by vogel76** [comment]
logged output:
testing stdout
testing stderr
2993690ms th_a       main.cpp:42                   load_config          ] config_file: C:/Users/vogel/AppData/Local/Invi
ctus Innovations, Inc/Keyhotee/default/config.json
2993788ms th_a       application.cpp:134           configure            ] external IP 89.78.59.252
2993789ms th_a       server.cpp:206                configure            ] listening for stcp connections on port 0
2993810ms th_a       bitname_db.cpp:92             load_indexes         ] load indexes
2993810ms th_a       bitname_db.cpp:107            load_indexes         ] load indexes
2993812ms th_a       bitname_db.cpp:162            init_timekeeper      ] ...init stats...
2993812ms th_a       bitname_db.cpp:164            init_timekeeper      ] ...done init timekeeper...
2993813ms th_a       bitname_db.cpp:214            open                 ] open name db
chain time: 20130822T183833
expected time: 20130822T183833
target difficulty: 256
target name difficulty: 256

**Comment by vogel76** [comment]
As a workaround (to continue work) config.json can be replaced with contents described in communicating_between_keyhotee_clients.txt document.

**Comment by dnotestein** [comment]
Bytemaster's latest commit corrects some problems, so now it's possible to connect to his server (which is running some older code, btw). You can still edit your config as described above to directly communicate between two local clients, but you'll also need to delete your bitname blockchains in your local profiles before connecting them, otherwise you'll hit the blockchain sync bug. I've added docs to communicating_between_keyhotee_clients.txt that describes this new required step.

If you do want to connect to the server, be sure you use a KeyhoteeId that's not already registered (e.g. don't use first or second, for example). Otherwise, you'll get an error during connection that tells you the id is already registered (which if you're on windows you probably will not yet see, since we don't have a diagnostic dialog yet to display this exception and we lose console window when application shuts down). KehoteeId mining is also slower when connected to the server (not sure of the reason for that, maybe network latency?). I haven't had a chance to test much behavior when connected to the remote server yet, but the fact that it's older code makes me think there will likely be problems (for example, I modified the size of messages by one byte for blank bcc list since the server was last compiled, I suspect).

**Comment by dnotestein** [comment]
Bytemaster, when you get a chance, please compile and startup a new server so that we can test server-based communication (email and chat). If that works well, hopefully we can close out this issue!
