### ISSUE TITLE
Inbox should display Date Sent, not Date Received. 

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#198]

**Comment by dnotestein** [comment]
Vogel and I both believe that the date received is more correct to show than date sent. But we can compromise by making the selected columns configurable so that user can select what columns to show in a mailbox. Thunderbird does this and I guess many other email clients do as well. Whoever gets assigned this should look at info available in message_header and see if there's any other columns we might optionally want to display that we don't display now.

**Comment by PaulEU** [comment]
Selecting columns should be also in the other mailbox: outbox, drafts, sent.
Selected columns should be stored and restored when program is started.

**Comment by PaulEU** [comment]
https://github.com/InvictusInnovations/keyhotee/commit/61425f71d3248ffe8cc48e389113a9758990f961
- Display "Date Sent" instead of "Date Received" in the inbox mail as default
- The User can configure displayed columns but for now inbox only
- Selected columns are not stored yet
