### ISSUE TITLE
wrong Keyhotee id is shown in from in a scenario

### ISSUE THREAD

**Issue by yuvarajgogoi** [InvictusInnovations/keyhotee#286]
Step to reproduce
1) create an Identity in a client.
2) now do send message.
3) save this message in drafts.
4) now delete the idenitity.
5) create a new idenity again.
6) open the draft message.

Check in from field. The Keyhotee id shown is different from the newly created id.

**Comment by PaulEU** [comment]
I checked this situation. I think is ok. Maybe problem was resolved in some commit. 
Yuvarajgogoi, could you check again you have still this problem ?

If I delete the identity in the mailbox is displayed public key instead of  Keyhotee id (it's ok because there in no KHID in database). Next if I create the same identity again Keyhotee id is displayed properly in the mailbox.
