### ISSUE TITLE
Eliminate ownership column and combine with icon functionality

### ISSUE THREAD

**Issue by dnotestein** [InvictusInnovations/keyhotee#60]
Eliminate separate ownership column. Instead we can modify the icons for contacts associated with identities (overlay some small gray square near bottom of icon with white letters saying "me") to indicate it's an identity rather than a normal contact.

**Comment by vogel76** [comment]
Proposed solution will have disadvantage: it will be impossible to sort contacts using 'ownership' column and this way display own ids in one group.

**Comment by bytemaster** [comment]
This can be implemented with a filter rather than by sorting.

**Comment by vogel76** [comment]
I suggest to leave it as is for Mileston 1, since separate column (with sort capabilities) can play as trivial filter (as I said user can group identities through sorting).
Before adding a filter we should first rethink its functionality - probably it should allow filtering by other columns also. It needs much more work, and first designing a gui for it.
What we can do right now - lets make this column smaller by eliminating its title (full title will be displayed on tooltip)

**Comment by dnotestein** [comment]
I think vogel's proposal (just dropping text column) is a reasonable interim solution for alpha release. I'd rather focus on other issues in next few days.

**Comment by vogel76** [comment]
Grzegorz please remove title for this column to make it smaller and setup tooltip to display its title on demand.

**Comment by grzegorzs** [comment]
Removed title for column Ownership and added tooltip.
5a25279c70a581ab75790ca4d74530f4f60e3b0a
