### ISSUE TITLE
Create new Contact should Never Display Contact List

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#63]
It will confuse the user to see a contact highlighted above while editing a new contact below.

**Comment by vogel76** [comment]
Let's hide upper panel, maximize lower one then. Also 'Show details' option should be grayed out while application is during 'new contact creation'.
Also if 'Show details' was disabled for given view, New Contact option should ignore this state and always show editing panel (right now nothing happens in GUI when detail pane is hidden)

**Comment by bytemaster** [comment]
I don't want the 'show details' button at all.   It makes the interface more complicated than necessary.  It should always be on, if you want details you can drag the separator to one end or the other.

**Comment by vogel76** [comment]
I think such 'show details' option can be better for users than simple splitter window resizing.
1) It allows simple closing/opening preview for contact/email contents without moving a splitter (what can be inconvinient on touch screens). Also application remembers lower pane size when opening it again.
2) Such option is useful IMHO also because of privacy - not all users would like to show automatically message contents/contact details and this could be achieved by hiding detail pane.

Also I don't think so it complicates the UI - this is just one of FEW basic options on main toolbar.

**Comment by dnotestein** [comment]
I think vogel raises some good points here, my vote is to leave the button in.

**Comment by PaulEU** [comment]
Create new contact - modifications
https://github.com/InvictusInnovations/keyhotee/commit/c00e653de543792e717aa817df89960f18212fcd
