### ISSUE TITLE
Unread Messages should have BOLD font in inbox.

### ISSUE THREAD

**Issue by bytemaster** [InvictusInnovations/keyhotee#92]
Description supplemented from very similar (marked as duplicated) issue: https://github.com/InvictusInnovations/keyhotee/issues/91
There is also another marker related to 'read' status: 'unread-status-icon' (blue circle in the dedicated column in mailbox table). This icon should be cleared when message has been already read/displayed when unread. Mailbox table should allow to sort contents by this column and ie fast group unread messages.

**Comment by vogel76** [comment]
To implement this feature we need API to persistently mark mail message (I assume object of type bts::bitchat::private_email_message) with some flags 'READ' etc (probably best to have wider field (int should be sufficient) than just bool flag allowing to mark message importance, favorite, reminder for example - as Outlook, Thunderbird).
Otherwise GUI of course can cache such info but it will disappear at application exit and after reopen all messages will be read what's wrong IMHO.

**Comment by vogel76** [comment]
As I see bts::bitchat::message_header contains a field called 'read_mark'. Please use it to do actual text formatting defined in this task.

**Comment by dnotestein** [comment]
Blue circle now indicates "unread" instead of read as of commit https://github.com/InvictusInnovations/keyhotee/commit/3508bf5230f6d31400682714f3d2259a8cee43fc

**Comment by grzegorzs** [comment]
Unread messages in bold and with blue circle
afa884c27f5b16ec13196a50660950e7f39e8d10
